version: '2'

volumes:
  ddns_logs:

services:
  my-node-ddns:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ddns_logs:/logs
    command: 'node app.js'
    restart: always

